### ISSUE TITLE
PortlandGeneralApi 400 Errors

### ISSUE THREAD

**Issue by ejpenney** [piekstra/portlandgeneral-api#6]
Hi,

For about a week or two I've been seeing these errors:

```
(.venv) root@dev:~/portlandgeneral-api# python example.py 
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword
POST https://api.portlandgeneral.com/pg-token-implicit/token
POST https://api.portlandgeneral.com/pge-graphql
Traceback (most recent call last):
  File "/root/portlandgeneral-api/example.py", line 16, in <module>
    info = client.get_account_info()
  File "/root/portlandgeneral-api/portlandgeneral/client.py", line 84, in get_account_info
    response_json = self._request_graphql(body=query)
  File "/root/portlandgeneral-api/portlandgeneral/client.py", line 63, in _request_graphql
    raise Exception(str(response.status_code) + ": " + response.reason + ": " + str(response.content))
Exception: 400: Bad Request: b'{"errors":[{"message":"Something unexpected happened."}]}\n'

```
At first I suspected there was an outage but as its persisted I'm wondering if PGE has changed something on their end?  The OPower API is still working fine, it looks like it's just the graphql stuff that's not working.

Is it just me?

**Comment by piekstra** [comment]
@ejpenney I will try and make some time to look into this during the weekend. Sorry to hear it's been experiencing errors for you. They've likely changed some API contract on their side.

**Comment by ejpenney** [comment]
No rush, I was able to get what I need from the OPower API, and things are working for me again.  Just figured I'd give you the heads up!
